# CMake generated Testfile for 
# Source directory: /Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/Rendering/Testing/Cxx
# Build directory: /Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Rendering/Testing/Cxx
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(otherCoordinate "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "otherCoordinate" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestPriorityStreaming "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestPriorityStreaming" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(LoadOpenGLExtension "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "LoadOpenGLExtension" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestActorLightingFlag "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestActorLightingFlag" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestAnimationScene "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestAnimationScene" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestBlurAndSobelPasses "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestBlurAndSobelPasses" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestDynamic2DLabelMapper "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestDynamic2DLabelMapper" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestFBO "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestFBO" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestGaussianBlurPass "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestGaussianBlurPass" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestGPUInfo "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestGPUInfo" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestGradientBackground "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestGradientBackground" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestInteractorTimers "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestInteractorTimers" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestLabelPlacer "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestLabelPlacer" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestLabelPlacer2D "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestLabelPlacer2D" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestLabelPlacerCoincidentPoints "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestLabelPlacerCoincidentPoints" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestLabelPlacementMapper2D "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestLabelPlacementMapper2D" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestLabelPlacementMapperCoincidentPoints "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestLabelPlacementMapperCoincidentPoints" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestLightActor "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestLightActor" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestLODActor "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestLODActor" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestManyActors "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestManyActors" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestOrderedTriangulator "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestOrderedTriangulator" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestOpacity "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestOpacity" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestOSConeCxx "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestOSConeCxx" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestPOVExporter "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestPOVExporter" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestResetCameraVerticalAspectRatio "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestResetCameraVerticalAspectRatio" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestResetCameraVerticalAspectRatioParallel "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestResetCameraVerticalAspectRatioParallel" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestSobelGradientMagnitudePass "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestSobelGradientMagnitudePass" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestShadowMapPass "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestShadowMapPass" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestTextActorAlphaBlending "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestTextActorAlphaBlending" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestTextActorDepthPeeling "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestTextActorDepthPeeling" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestTextActor3DAlphaBlending "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestTextActor3DAlphaBlending" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestTextActor3DDepthPeeling "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestTextActor3DDepthPeeling" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestTexturedBackground "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestTexturedBackground" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestTDx "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestTDx" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestTilingCxx "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestTilingCxx" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestTranslucentLUTAlphaBlending "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestTranslucentLUTAlphaBlending" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestTranslucentLUTDepthPeeling "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestTranslucentLUTDepthPeeling" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestTranslucentLUTDepthPeelingPass "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestTranslucentLUTDepthPeelingPass" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestTranslucentLUTTextureAlphaBlending "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestTranslucentLUTTextureAlphaBlending" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestTranslucentLUTTextureDepthPeeling "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestTranslucentLUTTextureDepthPeeling" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestGenericVertexAttributesGLSLCxx "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestGenericVertexAttributesGLSLCxx" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestGenericVertexAttributesGLSLAlphaBlending "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestGenericVertexAttributesGLSLAlphaBlending" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
ADD_TEST(TestGenericVertexAttributesGLSLDepthPeelingPass "/Developer/VTK/VTK-Build2/bin/RenderingCxxTests" "TestGenericVertexAttributesGLSLDepthPeelingPass" "-T" "/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Testing/Temporary")
SET_TESTS_PROPERTIES(TestGenericVertexAttributesGLSLDepthPeelingPass PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR:.*vtkOpenGLProperty.*Couldn't build the shader program. At this point , it can be an error in a shader or a driver bug.")
