# CMake generated Testfile for 
# Source directory: /Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/Infovis/Testing/Cxx
# Build directory: /Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Infovis/Testing/Cxx
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(Infovis-TestArcEdges "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestArcEdges")
ADD_TEST(Infovis-TestAssignCoordinates "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestAssignCoordinates")
ADD_TEST(Infovis-TestCollapseVerticesByArray "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestCollapseVerticesByArray")
ADD_TEST(Infovis-TestContingencyStatistics "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestContingencyStatistics")
ADD_TEST(Infovis-TestCorrelativeStatistics "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestCorrelativeStatistics")
ADD_TEST(Infovis-TestCosmicTreeLayoutStrategy "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestCosmicTreeLayoutStrategy")
ADD_TEST(Infovis-TestDataObjectToTable "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestDataObjectToTable")
ADD_TEST(Infovis-TestDescriptiveStatistics "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestDescriptiveStatistics")
ADD_TEST(Infovis-TestExtractSelectedGraph "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestExtractSelectedGraph")
ADD_TEST(Infovis-TestGraph "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestGraph")
ADD_TEST(Infovis-TestGraphAttributes "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestGraphAttributes")
ADD_TEST(Infovis-TestGraphAlgorithms "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestGraphAlgorithms")
ADD_TEST(Infovis-TestGraphHierarchicalBundle "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestGraphHierarchicalBundle")
ADD_TEST(Infovis-TestGraphLayoutStrategy "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestGraphLayoutStrategy")
ADD_TEST(Infovis-TestGroupLeafVertices "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestGroupLeafVertices")
ADD_TEST(Infovis-TestKdTreeBoxSelection "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestKdTreeBoxSelection")
ADD_TEST(Infovis-TestKMeansStatistics "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestKMeansStatistics")
ADD_TEST(Infovis-TestMergeGraphs "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestMergeGraphs")
ADD_TEST(Infovis-TestMultiCorrelativeStatistics "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestMultiCorrelativeStatistics")
ADD_TEST(Infovis-TestOrderStatistics "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestOrderStatistics")
ADD_TEST(Infovis-TestPassArrays "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestPassArrays")
ADD_TEST(Infovis-TestPassThrough "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestPassThrough")
ADD_TEST(Infovis-TestPCAStatistics "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestPCAStatistics")
ADD_TEST(Infovis-TestPruneTreeFilter "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestPruneTreeFilter")
ADD_TEST(Infovis-TestRandomGraphSource "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestRandomGraphSource")
ADD_TEST(Infovis-TestSimple3DCirclesStrategy "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestSimple3DCirclesStrategy")
ADD_TEST(Infovis-TestStreamGraph "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestStreamGraph")
ADD_TEST(Infovis-TestStringToCategory "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestStringToCategory")
ADD_TEST(Infovis-TestTable "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestTable")
ADD_TEST(Infovis-TestTableSplitColumnComponents "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestTableSplitColumnComponents")
ADD_TEST(Infovis-TestTreeMapLayoutStrategy "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestTreeMapLayoutStrategy")
ADD_TEST(Infovis-TestThresholdTable "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestThresholdTable")
ADD_TEST(Infovis-TestVariantArray "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestVariantArray")
ADD_TEST(Infovis-TestVariant "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestVariant")
ADD_TEST(Infovis-TestSQLGraphReader "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestSQLGraphReader")
ADD_TEST(Infovis-TestTimePoint "/Developer/VTK/VTK-Build2/bin/InfovisCxxTests" "TestTimePoint")
ADD_TEST(Array-ArrayAPIDenseCoordinates "/Developer/VTK/VTK-Build2/bin/InfovisArrayCxxTests" "ArrayAPIDenseCoordinates")
ADD_TEST(Array-ArrayDiagonalMatrixSource "/Developer/VTK/VTK-Build2/bin/InfovisArrayCxxTests" "ArrayDiagonalMatrixSource")
ADD_TEST(Array-ArrayDotProductSimilarity "/Developer/VTK/VTK-Build2/bin/InfovisArrayCxxTests" "ArrayDotProductSimilarity")
ADD_TEST(Array-ArrayExtractFactoredArray "/Developer/VTK/VTK-Build2/bin/InfovisArrayCxxTests" "ArrayExtractFactoredArray")
ADD_TEST(Array-ArrayMatricizeArray "/Developer/VTK/VTK-Build2/bin/InfovisArrayCxxTests" "ArrayMatricizeArray")
ADD_TEST(Array-TestArrayNorm "/Developer/VTK/VTK-Build2/bin/InfovisArrayCxxTests" "TestArrayNorm")
ADD_TEST(Array-ArrayNormalizeMatrixVectors "/Developer/VTK/VTK-Build2/bin/InfovisArrayCxxTests" "ArrayNormalizeMatrixVectors")
ADD_TEST(Array-ArraySparseArrayToTable "/Developer/VTK/VTK-Build2/bin/InfovisArrayCxxTests" "ArraySparseArrayToTable")
ADD_TEST(Array-ArrayTableToSparseArray "/Developer/VTK/VTK-Build2/bin/InfovisArrayCxxTests" "ArrayTableToSparseArray")
ADD_TEST(Array-ArrayToTable "/Developer/VTK/VTK-Build2/bin/InfovisArrayCxxTests" "ArrayToTable")
ADD_TEST(Array-ArrayTransposeMatrix "/Developer/VTK/VTK-Build2/bin/InfovisArrayCxxTests" "ArrayTransposeMatrix")
