/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkVolumeTextureMapper3D_FourDependentNoShadeFP string.
 *
 */
#ifndef __vtkVolumeTextureMapper3D_FourDependentNoShadeFP_h
#define __vtkVolumeTextureMapper3D_FourDependentNoShadeFP_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkVolumeTextureMapper3D_FourDependentNoShadeFP;

#endif /* #ifndef __vtkVolumeTextureMapper3D_FourDependentNoShadeFP_h */
