# CMake generated Testfile for 
# Source directory: /Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/Common/Testing/Cxx
# Build directory: /Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Developer/VTK/VTK-Build/Common/Testing/Cxx
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(ObjectFactory "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "ObjectFactory")
ADD_TEST(otherArrays "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "otherArrays")
ADD_TEST(otherTimerLog "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "otherTimerLog")
ADD_TEST(otherLookupTable "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "otherLookupTable")
ADD_TEST(otherLookupTableWithEnabling "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "otherLookupTableWithEnabling")
ADD_TEST(otherByteSwap "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "otherByteSwap")
ADD_TEST(otherStringArray "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "otherStringArray")
ADD_TEST(TestAmoebaMinimizer "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "TestAmoebaMinimizer")
ADD_TEST(TestArrayLookup "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "TestArrayLookup")
ADD_TEST(TestConditionVariable "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "TestConditionVariable")
SET_TESTS_PROPERTIES(TestConditionVariable PROPERTIES  RUN_SERIAL "ON")
ADD_TEST(TestGarbageCollector "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "TestGarbageCollector")
ADD_TEST(TestDataArray "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "TestDataArray")
ADD_TEST(TestDirectory "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "TestDirectory")
ADD_TEST(TestFastNumericConversion "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "TestFastNumericConversion")
ADD_TEST(TestMath "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "TestMath")
ADD_TEST(TestMatrix3x3 "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "TestMatrix3x3")
ADD_TEST(TestMinimalStandardRandomSequence "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "TestMinimalStandardRandomSequence")
ADD_TEST(TestPolynomialSolversUnivariate "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "TestPolynomialSolversUnivariate")
ADD_TEST(TestSmartPointer "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "TestSmartPointer")
ADD_TEST(TestSortDataArray "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "TestSortDataArray")
ADD_TEST(TestUnicodeStringAPI "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "TestUnicodeStringAPI")
ADD_TEST(TestUnicodeStringArrayAPI "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "TestUnicodeStringArrayAPI")
ADD_TEST(TestVariantComparison "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "TestVariantComparison")
ADD_TEST(SystemInformation "/Developer/VTK/VTK-Build2/bin/CommonCxxTests" "SystemInformation")
ADD_TEST(TestCxxFeatures "/Developer/VTK/VTK-Build2/bin/TestCxxFeatures")
ADD_TEST(TestInstantiator "/Developer/VTK/VTK-Build2/bin/TestInstantiator")
ADD_TEST(Array-ArrayAPI "/Developer/VTK/VTK-Build2/bin/ArrayCxxTests" "ArrayAPI")
ADD_TEST(Array-ArrayAPIConvenience "/Developer/VTK/VTK-Build2/bin/ArrayCxxTests" "ArrayAPIConvenience")
ADD_TEST(Array-ArrayAPIDense "/Developer/VTK/VTK-Build2/bin/ArrayCxxTests" "ArrayAPIDense")
ADD_TEST(Array-ArrayAPISparse "/Developer/VTK/VTK-Build2/bin/ArrayCxxTests" "ArrayAPISparse")
ADD_TEST(Array-ArrayBool "/Developer/VTK/VTK-Build2/bin/ArrayCxxTests" "ArrayBool")
ADD_TEST(Array-ArrayInterpolationDense "/Developer/VTK/VTK-Build2/bin/ArrayCxxTests" "ArrayInterpolationDense")
ADD_TEST(Array-ArrayNullValues "/Developer/VTK/VTK-Build2/bin/ArrayCxxTests" "ArrayNullValues")
ADD_TEST(Array-ArrayExtents "/Developer/VTK/VTK-Build2/bin/ArrayCxxTests" "ArrayExtents")
ADD_TEST(Array-ArrayUserTypes "/Developer/VTK/VTK-Build2/bin/ArrayCxxTests" "ArrayUserTypes")
ADD_TEST(Array-ArrayVariants "/Developer/VTK/VTK-Build2/bin/ArrayCxxTests" "ArrayVariants")
ADD_TEST(Array-SparseArrayValidation "/Developer/VTK/VTK-Build2/bin/ArrayCxxTests" "SparseArrayValidation")
