/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkGaussianBlurPassShader_fs string.
 *
 */
#ifndef __vtkGaussianBlurPassShader_fs_h
#define __vtkGaussianBlurPassShader_fs_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkGaussianBlurPassShader_fs;

#endif /* #ifndef __vtkGaussianBlurPassShader_fs_h */
