/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkLighting_s string.
 *
 */
#ifndef __vtkLighting_s_h
#define __vtkLighting_s_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkLighting_s;

#endif /* #ifndef __vtkLighting_s_h */
