/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkLightingHelper_s string.
 *
 */
#ifndef __vtkLightingHelper_s_h
#define __vtkLightingHelper_s_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkLightingHelper_s;

#endif /* #ifndef __vtkLightingHelper_s_h */
