/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkLineIntegralConvolution2D_fs string.
 *
 */
#ifndef __vtkLineIntegralConvolution2D_fs_h
#define __vtkLineIntegralConvolution2D_fs_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkLineIntegralConvolution2D_fs;

#endif /* #ifndef __vtkLineIntegralConvolution2D_fs_h */
