/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkOpenGLPropertyDefaultMain_vs string.
 *
 */
#ifndef __vtkOpenGLPropertyDefaultMain_vs_h
#define __vtkOpenGLPropertyDefaultMain_vs_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkOpenGLPropertyDefaultMain_vs;

#endif /* #ifndef __vtkOpenGLPropertyDefaultMain_vs_h */
