/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkOpenGLRenderer_PeelingFS string.
 *
 */
#ifndef __vtkOpenGLRenderer_PeelingFS_h
#define __vtkOpenGLRenderer_PeelingFS_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkOpenGLRenderer_PeelingFS;

#endif /* #ifndef __vtkOpenGLRenderer_PeelingFS_h */
