/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkShadowMapPassShader_fs string.
 *
 */
#ifndef __vtkShadowMapPassShader_fs_h
#define __vtkShadowMapPassShader_fs_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkShadowMapPassShader_fs;

#endif /* #ifndef __vtkShadowMapPassShader_fs_h */
