/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkShadowMapPassShader_vs string.
 *
 */
#ifndef __vtkShadowMapPassShader_vs_h
#define __vtkShadowMapPassShader_vs_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkShadowMapPassShader_vs;

#endif /* #ifndef __vtkShadowMapPassShader_vs_h */
