/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkSobelGradientMagnitudePassShader1_fs string.
 *
 */
#ifndef __vtkSobelGradientMagnitudePassShader1_fs_h
#define __vtkSobelGradientMagnitudePassShader1_fs_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkSobelGradientMagnitudePassShader1_fs;

#endif /* #ifndef __vtkSobelGradientMagnitudePassShader1_fs_h */
