/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkSobelGradientMagnitudePassShader2_fs string.
 *
 */
#ifndef __vtkSobelGradientMagnitudePassShader2_fs_h
#define __vtkSobelGradientMagnitudePassShader2_fs_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkSobelGradientMagnitudePassShader2_fs;

#endif /* #ifndef __vtkSobelGradientMagnitudePassShader2_fs_h */
