/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_CompositeCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_CompositeCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_CompositeCroppingFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_CompositeCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_CompositeCroppingFS_h */
