/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MIPCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MIPCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_MIPCroppingFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MIPCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MIPCroppingFS_h */
