/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_HeaderFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_HeaderFS_h
#define __vtkGPUVolumeRayCastMapper_HeaderFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_HeaderFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_HeaderFS_h */
