/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_CompositeNoCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_CompositeNoCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_CompositeNoCroppingFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_CompositeNoCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_CompositeNoCroppingFS_h */
