/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_CompositeFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_CompositeFS_h
#define __vtkGPUVolumeRayCastMapper_CompositeFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_CompositeFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_CompositeFS_h */
