/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MinIPFourDependentNoCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MinIPFourDependentNoCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_MinIPFourDependentNoCroppingFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MinIPFourDependentNoCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MinIPFourDependentNoCroppingFS_h */
