/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MinIPCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MinIPCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_MinIPCroppingFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MinIPCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MinIPCroppingFS_h */
