/* DO NOT EDIT.
 * Generated by /Volumes/Macintosh HD/Developer/VTK/VTK-Build2/bin/vtkEncodeString
 * 
 * Declare the vtkVolumeTextureMapper3D_OneComponentNoShadeFP string.
 *
 */
#ifndef __vtkVolumeTextureMapper3D_OneComponentNoShadeFP_h
#define __vtkVolumeTextureMapper3D_OneComponentNoShadeFP_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkVolumeTextureMapper3D_OneComponentNoShadeFP;

#endif /* #ifndef __vtkVolumeTextureMapper3D_OneComponentNoShadeFP_h */
